import { useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useAccount } from "wagmi";

import Head from "next/head";
import Link from "next/link";
import NoSSR from "react-no-ssr";
import Button from "~/components/ui/button";

export default function Home() {
  const session = useSession();
  const account = useAccount();
  const user = api.user.getUser.useQuery(undefined, {
    enabled: session.status === "authenticated",
  });

  const displayLinkWarning =
    (!!user.data && !user.data?.address && account.address) ||
    user.data?.address != account.address;

  return (
    <>
      <Head>
        <title>Pigeon MVP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen">
        <div className="container mt-14 flex flex-col items-center gap-12 px-4 pt-20">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to Pigeon <span className="text-accent">BETA</span>
          </h1>

          <NoSSR>
            {(!user.data ||
              !account.address ||
              session.status != "authenticated") && (
              <div className="flex flex-col justify-start gap-2 rounded-xl bg-yellow-700/90 px-4 py-4">
                <h2>Your account setup is not complete.</h2>
                <h3>
                  Please review <Link href="/profile">My Profile</Link> to
                  finish it.
                </h3>

                <Button
                  text="My Profile"
                  type="nextLink"
                  href="/profile"
                  styleType="accentOutline"></Button>
              </div>
            )}

            <div className="flex flex-col">
              {session.status === "authenticated" &&
                account.isConnected &&
                !displayLinkWarning && (
                  <>
                    <h2>How may we assist you?</h2>
                    <div className="flex flex-col gap-2">
                      <p className="py-4 text-xl">
                        By being a participant, you will create the agreement
                        and work with the driver.
                      </p>

                      <Button
                        text="Participate"
                        type="nextLink"
                        href="/app/participant"
                        styleType="accentOutline"></Button>

                      <p className="py-4 text-xl">
                        By being the courier, you will be responsible for
                        delivering to participants' needs.
                      </p>
                      <Button
                        text="Be a courier"
                        type="nextLink"
                        href="/aap/courier"
                        styleType="accentOutline"></Button>
                    </div>
                  </>
                )}
            </div>
          </NoSSR>
        </div>
      </main>
    </>
  );
}
